delete from volunteers where true;
delete from inventory where true;
delete from order_items where true;
delete from orders where true;
delete from deliveries where true;
delete from inventory where true;
delete from items where true;
delete from users where true;
delete from schools where true;
delete from wishlists where true;
alter sequence deliveries_id_seq restart with 1;
alter sequence inventory_id_seq restart with 1;
alter sequence items_id_seq restart with 1;
alter sequence order_items_id_seq restart with 1;
alter sequence orders_id_seq restart with 1;
alter sequence schools_id_seq restart with 1;
alter sequence users_id_seq restart with 1;
alter sequence volunteers_id_seq restart with 1;
alter sequence wishlists_id_seq restart with 1;
